#!/bin/bash

dd if=/dev/urandom of=./one-block bs=510 count=1
dd if=/dev/urandom of=./one-block-exactly bs=512 count=1

dd if=/dev/urandom of=./two-blocks bs=510 count=2
dd if=/dev/urandom of=./two-blocks-exactly bs=512 count=2

dd if=/dev/urandom of=./three-blocks bs=510 count=3
dd if=/dev/urandom of=./three-blocks-exactly bs=512 count=3

dd if=/dev/urandom of=./four-blocks bs=510 count=4
dd if=/dev/urandom of=./four-blocks-exactly bs=512 count=4

dd if=/dev/urandom of=./large-file bs=510 count=11
